-- SQL Query for filling in data to the member_majors table
INSERT INTO member_majors (studentid, major)
VALUES (1, 'Computer Science'),
    (2, 'Civil Engineering'),
    (3, 'Computer Engineering'),
    (3, 'Computer Science'),
    (4, 'Mechanical Engineering'),
    (5, 'Chemical Engineering'),
    (6, 'Aerospace Engineering'),
    (7, 'Mechanical Engineering'),
    (8, 'Computer Engineering'),
    (9, 'Computer Science'),
    (10, 'Civil Engineering'),
    (11, 'Computer Science'),
    (12, 'Mechanical Engineering'),
    (13, 'Mechanical Engineering'),
    (14, 'Computer Engineering'),
    (15, 'Computer Science'),
    (16, 'Chemical Engineering'),
    (16, 'Civil Engineering'),
    (17, 'Mechanical Engineering'),
    (18, 'Computer Science'),
    (19, 'Computer Engineering'),
    (20, 'Civil Engineering'),
    (21, 'Mechanical Engineering'),
    (21, 'Aerospace Engineering'),
    (22, 'Civil Engineering'),
    (23, 'Chemical Engineering'),
    (24, 'Computer Science'),
    (25, 'Civil Engineering');